services:
  - type: web_service
    name: interviewace-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://arunthak56388_db_user:Ankush4756@cluster01.mjpepw2.mongodb.net/sample_mflix?appName=Cluster01
      - key: JWT_SECRET
        value: InterviewAce2024SecretKey123!@
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://interviewace-frontend.onrender.com

  - type: static_site
    name: interviewace-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://interviewace-1-5zo7.onrender.com/api
